# Generated by Django 3.2.16 on 2023-02-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Days', '0002_alter_days_day_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='day_status',
            field=models.BooleanField(),
        ),
    ]
