# Generated by Django 3.2.9 on 2023-04-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='prog_rev_id',
        ),
    ]
