# Generated by Django 3.2.9 on 2023-04-27 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Program_Revision', '0001_initial'),
        ('Class', '0002_remove_class_prog_rev_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='prog_rev_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Program_Revision.program_revision'),
        ),
    ]
