# Generated by Django 3.2.16 on 2023-03-07 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        ('Program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='uni_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.university'),
        ),
    ]
