# Generated by Django 3.2.16 on 2023-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0003_rename_uni_id_program_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='prog_desc',
            field=models.CharField(max_length=2000),
        ),
    ]
