# Generated by Django 3.2.16 on 2023-03-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0004_alter_program_prog_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='user_id',
        ),
    ]
