# Generated by Django 3.2.16 on 2023-03-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0006_alter_program_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='prog_id',
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
