# Generated by Django 3.2.16 on 2023-03-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0007_auto_20230312_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='prog_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
