# Generated by Django 3.2.16 on 2023-04-06 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Program', '0008_program_prog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='initial_data',
            fields=[
                ('initial_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('tt_name', models.CharField(max_length=150)),
                ('prog_name', models.CharField(max_length=150)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
