# Generated by Django 3.2.9 on 2023-04-26 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0009_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0008_auto_20230426_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=40)),
                ('course_name', models.CharField(max_length=100)),
                ('course_semester', models.CharField(max_length=100)),
                ('course_year', models.CharField(max_length=100)),
                ('course_abbr', models.CharField(max_length=100)),
                ('prog_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Program.program')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
