# Generated by Django 3.2.9 on 2023-04-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_new_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_course',
            name='prog_id',
        ),
    ]
