# Generated by Django 3.2.9 on 2023-04-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_new_course_prog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_course',
            name='prog_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
