# Generated by Django 3.2.9 on 2023-04-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20230427_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_course_model',
            name='tt_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
