# Generated by Django 3.2.16 on 2023-02-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Program_Revision', '0002_alter_program_revision_prog_rev_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_revision',
            name='prog_rev_status',
            field=models.BooleanField(),
        ),
    ]
