# Generated by Django 3.2.16 on 2023-03-02 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Deliverables',
            fields=[
                ('cd_id', models.AutoField(primary_key=True, serialize=False)),
                ('cd_name', models.CharField(max_length=100)),
                ('cd_desc', models.CharField(max_length=1000)),
                ('cd_duration_min', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
