# Generated by Django 3.2.16 on 2023-02-07 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_deliverables', '0004_remove_course_deliverables_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Deliverables',
        ),
    ]
