# Generated by Django 3.2.16 on 2023-02-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_deliverables', '0009_course_deliverables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_deliverables',
            name='cd_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
