# Generated by Django 3.2.16 on 2023-02-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_deliverables', '0011_alter_course_deliverables_cd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_deliverables',
            name='cd_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
