# Generated by Django 3.2.16 on 2022-12-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('inst_id', models.AutoField(primary_key=True, serialize=False)),
                ('inst_name', models.CharField(max_length=100)),
                ('inst_admin_name', models.CharField(max_length=100)),
                ('inst_email', models.EmailField(max_length=254)),
                ('inst_admin_email', models.EmailField(max_length=254)),
                ('inst_contact', models.CharField(max_length=15)),
                ('inst_admin_contact', models.CharField(max_length=15)),
                ('inst_address', models.CharField(max_length=15)),
                ('passwd', models.CharField(max_length=15)),
            ],
        ),
    ]
