# Generated by Django 3.2.16 on 2022-12-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='inst_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='inst_admin_contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='inst_contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='passwd',
            field=models.CharField(max_length=100),
        ),
    ]
