# Generated by Django 3.2.16 on 2023-01-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221218_0727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institutions',
        ),
    ]
