# Generated by Django 3.2.16 on 2023-01-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_details_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='username',
            field=models.CharField(default='nothing', max_length=100),
        ),
    ]
