# Generated by Django 3.2.16 on 2023-01-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_details_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='username',
        ),
    ]
