# Generated by Django 3.2.16 on 2023-02-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_roles',
        ),
    ]
