# Generated by Django 3.2.9 on 2023-04-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
