# Generated by Django 3.2.9 on 2023-04-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DCapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input_values',
            old_name='no_classes',
            new_name='no_periods',
        ),
    ]
