# Generated by Django 3.2.9 on 2023-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCapp', '0003_input_values_tt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_values',
            name='id',
        ),
        migrations.AddField(
            model_name='input_values',
            name='DCapp_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
