# Generated by Django 3.2.16 on 2023-02-07 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Slot', '0001_initial'),
        ('Class', '0001_initial'),
        ('Days', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Schedule',
            fields=[
                ('cs_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Class.class')),
                ('day_id', models.ForeignKey(db_column='day_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Days.days')),
                ('slot_id', models.ForeignKey(db_column='slot_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Slot.slot')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
