# Generated by Django 3.2.16 on 2023-02-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slot', '0002_alter_slot_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='slot_status',
            field=models.BooleanField(),
        ),
    ]
