# Generated by Django 3.2.16 on 2023-03-12 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0006_course_user_id'),
        ('Program', '0008_program_prog_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0001_initial'),
        ('university', '0002_remove_university_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Program.program')),
                ('tt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable')),
                ('uni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
