# Generated by Django 3.2.9 on 2023-04-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='tt_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
