# Generated by Django 3.2.9 on 2023-04-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_mapping_tt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='id',
        ),
        migrations.AddField(
            model_name='mapping',
            name='mapping_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
